FROM ubuntu:18.04
RUN apt update \
    &&  apt install -y curl \
    &&  apt install -y net-tools \
    &&  apt install -y iputils-ping \
    &&  apt install -y unzip \
    &&  apt install -y wget \
    &&  apt install -y nginx nano\
    &&  mkdir /myapp
RUN useradd appuser    
WORKDIR /app    
COPY myscript.sh /myapp
ADD https://github.com/naraharisettysairam/terraformsingleinstance-1/archive/master.zip /myapp

EXPOSE 80 8080 8000
#CMD ping www.google.com
ENTRYPOINT ["ping", "-c 5"]
CMD ["www.google.com"]